Adding usage as search parameter in advanced search
ODNZSL/NZSL-signbank pull request #76
Opened 2022-06-29 21:49 UTC by Dimithri

JIRA Ticket: https://ackama.atlassian.net/browse/N2-144

This PR is to add `usage` as a search parameter in the advance search page.

![image](https://user-images.githubusercontent.com/5234605/176551359-25889daa-5c27-4f21-821a-e47da72f1e49.png)

2022-06-29 23:54 UTC, jonholdsworth approved these changes

2022-06-30 20:43 UTC, joshmcarthur requested changes

2022-06-30 20:43 UTC, joshmcarthur commented on signbank/dictionary/adminviews.py
> +            qs = Gloss.objects.filter(usage__id__in=vals)
You need to filter `qs` here, not `Gloss.objects`

```suggestion
            qs = qs.filter(usage__id__in=vals)
```

2022-07-03 23:30 UTC, joshmcarthur approved these changes

2022-07-04 00:25 UTC, merged