Adding location as a search parameter in advance search
ODNZSL/NZSL-signbank pull request #78
Opened 2022-06-30 04:32 UTC by Dimithri

JIRA Ticket: https://ackama.atlassian.net/browse/N2-148

This PR adds `location` as a search parameter to the advance search page. 

![image](https://user-images.githubusercontent.com/5234605/176593258-02e3afcd-71f4-4e42-9515-ea8ef5143be8.png)

2022-06-30 04:44 UTC, jonholdsworth approved these changes
Nicely done

2022-06-30 20:41 UTC, joshmcarthur requested changes

2022-06-30 20:41 UTC, joshmcarthur commented on signbank/dictionary/forms.py
> +    location = forms.ModelChoiceField(label=_('Location'), queryset=FieldChoice.objects.filter(field='location'),
If you specify [`to_field_name='machine_value'`](https://docs.djangoproject.com/en/4.0/ref/forms/fields/#django.forms.ModelChoiceField.to_field_name) here, you won't need to look up the field choice above, you can just pass it straight to your queryset

2022-07-03 23:37 UTC, joshmcarthur approved these changes

2022-07-04 00:14 UTC, merged