Adding example field search to advance search
ODNZSL/NZSL-signbank pull request #83
Opened 2022-07-04 05:45 UTC by Dimithri

JIRA Ticket: https://ackama.atlassian.net/browse/N2-147

This PR adds `strong_handshape` as a search parameter to advance search.

![image](https://user-images.githubusercontent.com/5234605/177088950-5a14a555-9deb-46f0-86c3-37123de1228f.png)

2022-07-04 07:36 UTC, jonholdsworth approved these changes

2022-07-04 23:32 UTC, joshmcarthur requested changes

2022-07-04 23:32 UTC, joshmcarthur commented on signbank/dictionary/adminviews.py
> +            val = '[' + val + ']'
Can you add a comment here to explain for future devs why we do this? We should have enough content in Slack to copy-paste some stuff here.

2022-07-05 00:05 UTC, jonholdsworth approved these changes

2022-07-05 01:36 UTC, joshmcarthur approved these changes
Great comment!

2022-07-05 01:38 UTC, merged