Updating sentry configuration
ODNZSL/NZSL-signbank pull request #96
Opened 2022-07-06 23:45 UTC by Dimithri

This PR has taken out the sentry configuration out of the `production.py`, so that the sentry error monitoring will happen for any environment which has the variable `SENTRY_DSN` is stored.

2022-07-06 23:57 UTC, jonholdsworth approved these changes

2022-07-07 00:06 UTC, joshmcarthur requested changes

2022-07-07 00:06 UTC, joshmcarthur commented on signbank/settings/base.py
> +import sentry_sdk
I think you should not even import sentry if there is no sentry DSN set.

2022-07-10 23:39 UTC, joshmcarthur approved these changes

2022-07-12 01:26 UTC, merged